# Deployment do api-test-junit5
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-test-junit5
spec:
  replicas: 5
  selector:
    matchLabels:
      app: api-test-junit5
  template:
    metadata:
      labels:
        app: api-test-junit5
    spec:
      containers:
        - name: api-test-junit5
          image: rodrigogoahead/api-test-junit5:v2

---
apiVersion: v1
kind: Service
metadata:
  name: api-test-junit5
spec:
  selector:
    app: api-test-junit5
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30000
  type: NodePort





